version: 0.2

phases:
  build:
    commands:
      - bundle install
      - ruby tests/app/test_web_api.rb
      - ruby tests/app/test_event_handlers.rb
      - cd app
      - bundle install --gemfile Gemfile
      - bundle install --gemfile Gemfile --deployment
      - cd ..
      - aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket $SOURCE_BUCKET_NAME

artifacts:
  type: zip
  files:
    - packaged.yaml
